name: archs
noise_path: data/HF_dataset_v2_background
drone_path: data/HF_dataset_v2_drone
description: Test model architectures with multinoise background, 5.12s clips
base_flags: --lr 1e-4 --clip-seconds 5.12 --spec-augment-prob 0.3 --epochs 15 --patience 0 --noise2 data/hf_dataset_sharded_expanded 
configs:
  - name: "01_resnet50"
    flags: --arch resnet50
  - name: "02_resnet18"
    flags: --arch resnet18
  - name: "03_convnext_small"
    flags: --arch convnext_small
  - name: "04_convnext_tiny"
    flags: --arch convnext_tiny
  - name: "05_efficientnet_lite0"
    flags: --arch efficientnet_lite0
  - name: "06_mobilevit_s"
    flags: --arch mobilevit_s
  - name: "07_efficientnet_lite4"
    flags: --arch efficientnet_lite4
  - name: "08_cnn14_deep"
    flags: --arch cnn14_deep
  - name: "09_mobilenetv4_conv_medium"
    flags: --arch mobilenetv4_conv_medium
  - name: "10_efficientnet_b1"
    flags: --arch efficientnet_b1